AWSTemplateFormatVersion: "2010-09-09"
Description: Creates Apollo GraphQL Server through API Gateway & Lambda.
Transform: "AWS::Serverless-2016-10-31"
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: "Prod"
      Cors:
        AllowCredentials: True
        AllowHeaders: "'content-type'"
        AllowMethods: "'GET,OPTIONS,POST'"
        AllowOrigin: "'https://studio.apollographql.com'"
        MaxAge: 31536000
  GraphqlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/main.graphqlHandler
      Runtime: nodejs14.x
      Events:
        Api:
          Type: Api
          Properties:
            Method: ANY
            Path: /graphql
            RestApiId:
              Ref: ApiGatewayApi
Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
