name: 'Build & Deploy'
env:
  ORG: rdokos
  NAME: serverless-graphql
  AWS_DEFAULT_REGION: eu-west-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        required: false
        description: "Allowed values: prod, test"
        default: prod
jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Prepare environment variables
        id: env
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          [ "$ENVIRONMENT" = "" ] && ENVIRONMENT=test
          if [ "$ENVIRONMENT" == "test" ]; then
            echo "TODO: additional test params to override"
          elif [ "$ENVIRONMENT" == "prod" ]; then
            echo "TODO: additional prod params to override"
          else
            printf '%s\n' "ENVIRONMENT is not in accepted range: test, prod." >&2
            exit 1
          fi
          echo ::set-output name=name::"${NAME}"
          echo ::set-output name=stack-name::"${ORG}-${ENVIRONMENT}-${NAME}"
          echo ::set-output name=cicd-bucket::"${ORG}-${ENVIRONMENT}-cicd-${AWS_DEFAULT_REGION}"
      - run: npm ci --frozen-lockfile
      - run: npm run test
      - name: Build
        run: |
          npm prune --production
          sam build
      - name: Deploy
        run: |
          sam deploy \
            --s3-bucket "${{ steps.env.outputs.cicd-bucket }}" \
            --s3-prefix "${{ steps.env.outputs.name }}" \
            --stack-name "${{ steps.env.outputs.stack-name }}" \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset
